apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-komsco-ai-dev-to-lightspeed-app-server
  namespace: openshift-lightspeed
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: komsco-ai-dev
          podSelector:
            matchLabels:
              app: komsco-ai-gateway
      ports:
        - port: 8443
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: application-server
      app.kubernetes.io/name: lightspeed-service-api
      app.kubernetes.io/part-of: openshift-lightspeed
  policyTypes:
    - Ingress
