---
plugin:
  name: ""
  displayName: ""
  description: ""
  image: ""
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  replicas: 2
  port: 9443
  securityContext:
    enabled: true
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
  basePath: /
  applicationMenu:
    enabled: true
    name: komsco-aiops-application-menu
    section: Cywell
    text: AIOps for OCP
    href: https://aiops.cywell.co.kr
    imageURL: data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2064%2064%22%3E%3Crect%20width%3D%2264%22%20height%3D%2264%22%20rx%3D%2214%22%20fill%3D%22%2306131f%22%2F%3E%3Crect%20x%3D%2212%22%20y%3D%2212%22%20width%3D%2240%22%20height%3D%2240%22%20rx%3D%2212%22%20fill%3D%22%23081827%22%20stroke%3D%22%23334155%22%20stroke-width%3D%222%22%2F%3E%3Cpath%20d%3D%22M32%2015%2049%2032%2032%2049%2015%2032%2032%2015Z%22%20fill%3D%22none%22%20stroke%3D%22%2338d6c1%22%20stroke-width%3D%224%22%20stroke-linejoin%3D%22round%22%2F%3E%3Cpath%20d%3D%22M23%2039%2031%2022h3l8%2017h-5l-1.3-3h-6.5l-1.2%203h-5Zm7.7-7h3.7L32.5%2027%2030.7%2032Z%22%20fill%3D%22%23e5faff%22%2F%3E%3Ccircle%20cx%3D%2232%22%20cy%3D%2232%22%20r%3D%2212%22%20fill%3D%22none%22%20stroke%3D%22%2338d6c1%22%20stroke-opacity%3D%22.18%22%20stroke-width%3D%224%22%2F%3E%3C%2Fsvg%3E
  certificateSecretName: ""
  gateway:
    alias: ai-gateway
    name: komsco-ai-gateway
    namespace: ""
    port: 8443
    authorization: UserToken
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  patcherServiceAccount:
    create: true
    annotations: {}
    name: ""
  jobs:
    patchConsoles:
      enabled: true
      image: "registry.redhat.io/openshift4/ose-tools-rhel9@sha256:ee65b244fc94d5765514c604dc0a288517dcdce68de65128d047622b6b30a618"
      podSecurityContext:
        enabled: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        enabled: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
