apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - lightspeed-networkpolicy.yaml
  - namespace.yaml
images:
  - name: komsco-ai-gateway
    newName: image-registry.openshift-image-registry.svc:5000/komsco-ai/komsco-ai-gateway
    newTag: "0.1.0"
patches:
  - target:
      kind: ServiceAccount
      name: komsco-ai-action-executor
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: Service
      name: komsco-ai-action-executor
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: Deployment
      name: komsco-ai-action-executor
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: NetworkPolicy
      name: komsco-ai-action-executor-ingress
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: ClusterRoleBinding
      name: komsco-ai-action-executor
    patch: |-
      - op: replace
        path: /metadata/name
        value: komsco-ai-action-executor
      - op: replace
        path: /subjects/0/namespace
        value: komsco-ai
  - target:
      kind: ServiceAccount
      name: komsco-ai-gateway
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: ConfigMap
      name: komsco-ai-service-ca
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: Service
      name: komsco-ai-gateway
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: Deployment
      name: komsco-ai-gateway
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: NetworkPolicy
      name: komsco-ai-gateway-ingress
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: ClusterRoleBinding
      name: komsco-ai-gateway-auth-delegator
    patch: |-
      - op: replace
        path: /metadata/name
        value: komsco-ai-gateway-auth-delegator
      - op: replace
        path: /subjects/0/namespace
        value: komsco-ai
  - target:
      kind: ServiceAccount
      name: komsco-ai-host-diagnostics-controller
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: ServiceAccount
      name: komsco-ai-host-diagnostics-runner
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: Role
      name: komsco-ai-host-diagnostics-controller
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: RoleBinding
      name: komsco-ai-host-diagnostics-controller
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
      - op: replace
        path: /subjects/0/namespace
        value: komsco-ai
  - target:
      kind: Service
      name: komsco-ai-host-diagnostics-controller
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: Deployment
      name: komsco-ai-host-diagnostics-controller
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: image-registry.openshift-image-registry.svc:5000/komsco-ai/komsco-ai-gateway:0.1.0
  - target:
      kind: NetworkPolicy
      name: komsco-ai-host-diagnostics-controller-ingress
    patch: |-
      - op: add
        path: /metadata/namespace
        value: komsco-ai
  - target:
      kind: ClusterRoleBinding
      name: komsco-ai-host-diagnostics-runner-scc
    patch: |-
      - op: replace
        path: /metadata/name
        value: komsco-ai-host-diagnostics-runner-scc
      - op: replace
        path: /subjects/0/namespace
        value: komsco-ai
