apiVersion: v1
kind: Service
metadata:
  name: komsco-ai-host-diagnostics-controller
  labels:
    app: komsco-ai-host-diagnostics-controller
spec:
  selector:
    app: komsco-ai-host-diagnostics-controller
  ports:
    - name: http
      port: 8080
      targetPort: http
