apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - action-executor-deployment.yaml
  - action-executor-networkpolicy.yaml
  - action-executor-rbac.yaml
  - action-executor-service.yaml
  - action-executor-serviceaccount.yaml
  - gateway-ca-configmap.yaml
  - gateway-deployment.yaml
  - gateway-networkpolicy.yaml
  - gateway-rbac.yaml
  - gateway-service.yaml
  - gateway-serviceaccount.yaml
