apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-ca-configmap.yaml
  - gateway-deployment.yaml
  - gateway-rbac.yaml
  - gateway-service.yaml
  - gateway-serviceaccount.yaml
