// v2 mock/sample records only. These are not live Gateway state.
import type { AiopsRecord, QueueItem } from '../../types';
import type { AlertEventRow, KnowledgeDoc, ReportItem } from './model';

export const mockExecutionRecords: AiopsRecord[] = [
  {
    kind: 'ActionProposal',
    metadata: { createdAt: '2026-07-03T09:02:00+09:00', name: 'crashloop-remediation-proposal' },
    spec: {
      action: 'restart_rollout',
      actor: 'aiops-gateway',
      evidenceId: 'evidence-crashloop-001',
      gate: 'Approval',
      result: 'proposed',
      status: { phase: 'proposed' },
      target: { kind: 'Deployment', namespace: 'komsco-ai-dev', name: 'aiops-scenario-1-crashloop' },
    },
  },
  {
    kind: 'SealedActionPlan',
    metadata: { createdAt: '2026-07-03T09:05:00+09:00', name: 'readiness-recovery-sealed-plan' },
    spec: {
      action: 'seal_mutation_plan',
      actor: 'aiops-gateway',
      evidenceId: 'evidence-readiness-002',
      gate: 'Approval Seal',
      result: 'waiting_approval',
      status: { phase: 'sealed_pending_approval' },
      target: { kind: 'Deployment', namespace: 'cyntra', name: 'cyntra-api' },
    },
  },
  {
    kind: 'ApprovalDecision',
    metadata: { createdAt: '2026-07-03T09:07:00+09:00', name: 'readiness-probe-approval' },
    spec: {
      action: 'approve_mutation',
      actor: 'platform-operator',
      auditId: 'audit-approval-003',
      gate: 'Approval',
      result: 'approved',
      approvalDecision: { status: 'approved' },
      target: { kind: 'Pod', namespace: 'cyntra', name: 'cyntra-api-5c747b5966-pn9gk' },
    },
  },
  {
    kind: 'ExecutionRecord',
    metadata: { createdAt: '2026-07-03T09:10:00+09:00', name: 'rollout-restart-execution' },
    spec: {
      action: 'rollout_restart',
      actor: 'action-executor',
      auditId: 'audit-mutation-004',
      evidenceId: 'evidence-mutation-004',
      gate: 'Executor',
      result: 'succeeded',
      mutationOutcome: { status: 'mutation_succeeded' },
      target: { kind: 'Deployment', namespace: 'komsco-ai-dev', name: 'aiops-two-pod-exec' },
    },
  },
];

export const mockAuditRecords: AiopsRecord[] = [
  {
    kind: 'AuditRecord',
    metadata: { createdAt: '2026-07-03T09:01:00+09:00', name: 'chat-request-accepted' },
    spec: {
      action: 'chat_request_accepted',
      actor: 'ocp-admin',
      auditId: 'audit-intake-001',
      gate: 'Gateway',
      requestId: 'request-crashloop-001',
      result: 'accepted',
      runId: 'crashloop-remediation',
      target: { kind: 'Run', namespace: 'komsco-ai-dev', name: 'crashloop-remediation' },
    },
  },
  {
    kind: 'AuditRecord',
    metadata: { createdAt: '2026-07-03T09:04:00+09:00', name: 'evidence-collected' },
    spec: {
      action: 'evidence_collected',
      actor: 'aiops-gateway',
      auditId: 'audit-evidence-002',
      evidenceId: 'evidence-crashloop-001',
      gate: 'Diagnostics',
      requestId: 'request-crashloop-001',
      result: 'collected',
      runId: 'crashloop-remediation',
      target: { kind: 'Evidence', namespace: 'komsco-ai-dev', name: 'crashloop-pod-status' },
    },
  },
  {
    kind: 'AuditRecord',
    metadata: { createdAt: '2026-07-03T09:08:00+09:00', name: 'approval-recorded' },
    spec: {
      action: 'approval_recorded',
      actor: 'platform-operator',
      auditId: 'audit-approval-003',
      gate: 'Ledger',
      requestId: 'request-crashloop-001',
      result: 'recorded',
      runId: 'crashloop-remediation',
      target: { kind: 'Approval', namespace: 'komsco-ai-dev', name: 'readiness-probe-approval' },
    },
  },
];

export const sampleRcaQueues: QueueItem[] = [
  {
    id: 'sample-rca-cluster-update-blocked',
    title: '샘플: 클러스터 업데이트 차단',
    category: '클러스터 버전',
    detail: '현재 4.20.23 · 추천 업데이트 4.20.26, 4.20.25 · AdminAckRequired',
    evidence: [
      'current 4.20.23',
      'recommended updates 4.20.26, 4.20.25',
      'conditional updates 4.20.24',
      'reason AdminAckRequired',
      'issues 1',
    ],
    source: '샘플 데이터',
    target: 'ClusterVersion/version',
    updatedAt: '07. 03. 오전 09:40',
    severity: 'warn',
  },
  {
    id: 'sample-rca-api-latency',
    title: '샘플: API 응답 지연 조사',
    category: '샘플 RCA',
    detail: '서비스 p95 지연 1.8s · 최근 배포 직후 증가 · 파드 재시작 없음',
    evidence: [
      'target cyntra/cyntra-api',
      'cpu 82%',
      'memory 71%',
      'reason readiness probe latency increased',
      'issues 1',
    ],
    source: '샘플 데이터',
    target: 'cyntra/cyntra-api',
    updatedAt: '07. 03. 오전 09:30',
    severity: 'warn',
  },
  {
    id: 'sample-rca-node-pressure',
    title: '샘플: 워커 노드 디스크 압박',
    category: '샘플 RCA',
    detail: 'worker-2 DiskPressure · 이미지 캐시 증가 · evict 후보 파드 3개',
    evidence: [
      'target worker-2',
      'kind Node',
      'reason DiskPressure=True',
      'issues 3',
    ],
    source: '샘플 데이터',
    target: 'worker-2',
    updatedAt: '07. 03. 오전 09:24',
    severity: 'risk',
  },
];

export const sampleKnowledgeDocs: KnowledgeDoc[] = [
  {
    category: '장애 대응',
    chunks: 12,
    id: 'runbook-crashloop',
    keywords: ['CrashLoopBackOff', 'BackOff', 'restart count', 'exit code', 'image pull'],
    linkedIssues: ['Pods degraded', 'Deployment availability drift', 'CrashLoopBackOff detected'],
    owner: 'AIOps 운영팀',
    rcaLinks: 3,
    searchStatus: '색인 완료',
    status: '검증됨',
    targetScopes: ['Pod', 'Deployment', 'ReplicaSet', 'RCA'],
    title: 'CrashLoopBackOff 파드 대응 런북',
    updatedAt: '07. 03. 오전 09:20',
    verifiedAt: '07. 03. 오전 09:20',
    version: 'v1.7',
    summary: '반복 재시작 파드의 이벤트, 로그, 최근 배포 변경을 분리해 확인하는 표준 절차입니다.',
    tags: ['Pod', 'Deployment', 'RCA'],
    steps: ['최근 이벤트와 종료 코드를 확인합니다.', '동일 ReplicaSet 내 Pod 상태와 로그를 비교합니다.', '배포 변경, 이미지 pull, probe 실패를 분리합니다.', '승인 게이트 필요 시 변경 요청을 생성합니다.'],
  },
  {
    category: '변경 통제',
    chunks: 8,
    id: 'policy-approval',
    keywords: ['approval gate', 'audit', 'change request', '자동 조치', '승인 정책'],
    linkedIssues: ['조치 승인 대기', 'Runbook gate required'],
    owner: '플랫폼 아키텍트',
    rcaLinks: 2,
    searchStatus: '색인 완료',
    status: '검증됨',
    targetScopes: ['Approval', 'Audit', 'Runbook', 'Policy'],
    title: 'AIOps 조치 승인 정책',
    updatedAt: '07. 02. 오후 05:40',
    verifiedAt: '07. 02. 오후 05:40',
    version: 'v2.1',
    summary: '자동 조치 제안, 승인 검증, 실행 원장 기록에 필요한 운영 통제 기준입니다.',
    tags: ['Approval', 'Audit', 'Policy'],
    steps: ['읽기/증거 수집 단계와 변경 실행 단계를 분리합니다.', '운영자 승인 없이 클러스터 변경을 실행하지 않습니다.', '모든 실행 결과는 감사 원장에 남깁니다.'],
  },
  {
    category: '업데이트',
    chunks: 10,
    id: 'ocp-update-check',
    keywords: ['ClusterVersion', 'Upgradeable=False', 'AdminAck', 'conditional update', '4.20'],
    linkedIssues: ['OCP 업데이트 사전 확인 필요', 'Admin acknowledgement required'],
    owner: 'OpenShift 운영팀',
    rcaLinks: 1,
    searchStatus: '검증 필요',
    status: '검증 필요',
    targetScopes: ['ClusterVersion', 'Update', 'AdminAck', 'Operator'],
    title: 'OCP 업데이트 차단 사전 점검',
    updatedAt: '07. 01. 오후 02:10',
    verifiedAt: '07. 01. 오후 02:10',
    version: 'v0.9',
    summary: 'ClusterVersion Upgradeable=False, AdminAck, conditional update 항목을 점검하는 문서입니다.',
    tags: ['ClusterVersion', 'Update', 'AdminAck'],
    steps: ['ClusterVersion condition을 확인합니다.', '추천 업데이트와 조건부 업데이트를 분리합니다.', 'AdminAck 또는 mirror signature 준비 여부를 확인합니다.'],
  },
];

export const sampleReportItems: ReportItem[] = [
  {
    id: 'daily-ops',
    title: '일일 운영 브리핑',
    subtitle: 'Daily Operations Brief',
    period: '오늘 00:00 - 현재',
    status: '생성 가능',
    statusDetail: '현재 상태 기준 즉시 생성',
    metric: '운영 상태',
    summary: '클러스터 건강도, 주요 이슈, AIOps 실행 기록을 한 페이지로 요약합니다.',
    sections: ['건강도 추이', '주요 이슈', '실행 권장', '미해결 알림'],
    requiredData: ['Cluster summary', 'Issue queue', 'AIOps activity'],
    outputs: ['HTML', 'PDF 출력', 'DOCX 준비 중'],
  },
  {
    id: 'rca-pack',
    title: 'RCA 증거 패키지',
    subtitle: 'RCA Evidence Package · 감사 제출용',
    period: '선택 이슈 기준',
    status: '이슈 선택 필요',
    statusDetail: '이슈 큐 선택 후 생성',
    metric: '감사 대응',
    summary: '이슈 큐, 증거 스트림, 실행 기록을 감사 제출용 형태로 묶는 보고서입니다.',
    sections: ['이슈 요약', '증거 패키지', '의존성 경로', '런북 게이트', '실행 기록'],
    requiredData: ['Selected issue', 'RCA evidence', 'Audit ledger'],
    outputs: ['HTML', 'PDF 출력', 'DOCX 준비 중'],
  },
  {
    id: 'monthly-capacity',
    title: '월간 리소스 및 용량 리포트',
    subtitle: 'Monthly Capacity Report',
    period: '최근 30일',
    status: '준비 중',
    statusDetail: '30일 이상 메트릭 수집 필요',
    metric: '용량 계획',
    summary: '노드, 파드, 컨트롤러, 스토리지 리소스 상태를 용량 계획 관점으로 정리합니다.',
    sections: ['리소스 분포', '이슈 빈도', '증설 후보', '용량 계획'],
    requiredData: ['30일 metrics', 'Resource inventory', 'Storage status'],
    outputs: ['HTML 샘플', 'PDF 출력', '예약 설정 준비 중'],
  },
];

export const sampleAlertEvents: AlertEventRow[] = [
  {
    category: '샘플',
    detail: '게이트웨이 이벤트 스트림이 비어 있을 때 보이는 예시 이벤트입니다.',
    id: 'sample-event-gateway-empty',
    namespace: 'komsco-ai-dev',
    sample: true,
    severity: 'warn',
    source: '샘플 데이터',
    target: 'aiops-gateway',
    time: '07. 03. 오전 09:35',
    title: '샘플: 이벤트 수집 지연',
  },
  {
    category: '샘플',
    detail: '파드 재시작 증가를 알림/이벤트 화면에서 확인하는 예시입니다.',
    id: 'sample-event-pod-restart',
    namespace: 'cyntra',
    sample: true,
    severity: 'risk',
    source: '샘플 데이터',
    target: 'cyntra-api',
    time: '07. 03. 오전 09:28',
    title: '샘플: 파드 재시작 급증',
  },
];
